### ISSUE TITLE
Filter person_id to only those ones appearing in the cdm$person table

### ISSUE THREAD

**Issue by martaalcalde** [oxford-pharmacoepi/OmopSketch#21]

**Comment by catalamarti** [comment]
may be fix in omopgenerics: https://github.com/darwin-eu-dev/omopgenerics/issues/435

**Comment by martaalcalde** [comment]
In Eunomia database, some of the cdm tables (i.e., observation_period), include participants that are not included in the person_id table. 

TBD if we incorporate  that only participants that appear in the person_id table are counted in our functions (+ a warning in case we do have to filter). The following functions are affected:
- summariseInObservation()
- summariseClinicalRecords()
- summariseObservationPeriod()
- summariseRecordCounts()

Functions under development that will be affected include:
- summariseEntryCharacteristics() // summarisePopulationCharacteristics()
- summariseCodeUse()

**Comment by martaalcalde** [comment]
this would be something relatively easy to implement at the beginning of the previous functions. @catalamarti should we go for this?

**Comment by catalamarti** [comment]
Create internal function that subsets the cdm tables of interest to the population defined in person table.

```
filterToPersonTable <- function(x) {
  cdm <- omopgenerics::cdmReference(x)
  id <- omopgenerics::personIdentifier(x)
  x |>
    dplyr::inner_join(
      cdm$person |>
        dplyr::select(!!id := "person_id"),
      by = id
    )
}
```

In the future this function shouldn't be used as omopgenerics will take care of this.
