### ISSUE TITLE
min, max values are not ploted when using tableOmopTable()

### ISSUE THREAD

**Issue by martaalcalde** [oxford-pharmacoepi/OmopSketch#22]

**Comment by martaalcalde** [comment]
@catalamarti should we add an argument in tableOmopTable() asking people to provide estimateNameFormat (argument from the function: https://darwin-eu.github.io/visOmopResults/reference/formatEstimateName.html)? 

The default value can be: 
      estimateNameFormat = c(
        "N (%)" = "<count> (<percentage>%)",
        "N"     = "<count>",
        "median [IQR]" = "<median> [<q25> - <q75>]",
        "mean (sd)" = "<mean> (<sd>)"
      )

**Comment by catalamarti** [comment]
I would not work much in table functions details, just that they work for the moment. @martaalcalde 

There will be a sprint in visOmopResults to try to unify all table behavior, we can work on tat when this sprint takes place
