### ISSUE TITLE
summariseTableCounts(), add stratification by age group

### ISSUE THREAD

**Issue by martaalcalde** [oxford-pharmacoepi/OmopSketch#23]

**Comment by martaalcalde** [comment]
when using ageGroup, if the input is `ageGroup = list("<65" = c(0,64), ">=65" = c(65,Inf))`, do we have to create an "overall" group?

**Comment by catalamarti** [comment]
I would always output an overall for the moment @martaalcalde

**Comment by martaalcalde** [comment]
so no ageGroup argument at the moment?

**Comment by catalamarti** [comment]
yes ageGroup, always dsplay overall too

**Comment by catalamarti** [comment]
I would use addAgeGroupQuery()
