### ISSUE TITLE
sort percentages in ascendant way

### ISSUE THREAD

**Issue by catalamarti** [oxford-pharmacoepi/OmopSketch#27]
It would be nice if we could sort the percentages ascendant:
![image](https://github.com/oxford-pharmacoepi/OmopSketch/assets/18575244/6a93fe09-1297-4eb2-9233-6b1ab402ef7e)

If I am not mistaken (tagging @nmercadeb to correct me) the order of rows is taken from the summarise_result. So it would be nice if we can do this in the postprocess of the results @martaalcalde

**Comment by nmercadeb** [comment]
Yes, I think it is as you described!

**Comment by martaalcalde** [comment]
This affects tableClinicalRecords() function.

**Comment by catalamarti** [comment]
- sort percentages internally in tableClinicalRecords before calling the visOmopResults::visOmopTable function
