### ISSUE TITLE
Create summariseConceptCounts()

### ISSUE THREAD

**Issue by martaalcalde** [oxford-pharmacoepi/OmopSketch#37]
- Stratify by age and sex

**Comment by catalamarti** [comment]
discuss differences with `summariseCodeUse` if any. options:
- reexport summariseCodeUse
- move summariseCodeUse to omopSketch
- include in a vignette summariseCodeUse

Do we want to stratify by year and age/sex at the same time?

**Comment by martaalcalde** [comment]
(Please @catalamarti confirm)

Decided with Marti that we would proceed as:

- copy summariseCodeUse() from CodelistGenerator package
```
summariseCodeUse(
  x,
  cdm,
  [c](https://rdrr.io/r/base/c.html)ountBy = c("record", "person"),
  byConcept = TRUE,
  byYear = FALSE,
  bySex = FALSE,
  ageGroup = NULL
)
```
- if x is not specified, all the codes in the concept table are summarised
- modify the arguments so they fit the standard of omopSketch
- Currently, the previous function doesn't allow for multiple strata at the same time (i.e., if you stratify by sex and year, it is stratified as women & overall, male & overall, overall & 1997, etc -> change it so strata is mixed


Once this is done, we will proceed with issue #70
