### ISSUE TITLE
Strata variable insted of ageGroup and sex

### ISSUE THREAD

**Issue by martaalcalde** [oxford-pharmacoepi/OmopSketch#44]
Would it be interesting to have a strata variable (as summariseCharacteristics) instead of specify ageGroup and sex?

**Comment by martaalcalde** [comment]
@catalamarti

**Comment by martaalcalde** [comment]
Or at least to have ageGroup & sex variable?

**Comment by catalamarti** [comment]
in which function?
so strata is nice if they can easily add stuff, which I dont hink it is the case @martaalcalde
