### ISSUE TITLE
add flextable option in table functions

### ISSUE THREAD

**Issue by martaalcalde** [oxford-pharmacoepi/OmopSketch#61]

**Comment by martaalcalde** [comment]
This issue affects the following functions:
- tableClinicalRecords()
- tableObservationPeriod()

To create both tables we used visOmopResult package. However, one of the features that this package has is that tables can be built using either gtable or flextable. Currently, only gtable is allowed in the omopSketch functions. Hence, we need to incorporate and argument that let the user choose between gtable (by default) or flextable, and incorporate the functionality.

**Comment by catalamarti** [comment]
Table function should be a call to `visOmopResults::visOmopTable` and one of the arguments that we should export it should be `type`, by default set type to "gt"
