### ISSUE TITLE
summarisePopulationCharacteristics

### ISSUE THREAD

**Issue by catalamarti** [oxford-pharmacoepi/OmopSketch#72]
```
summarisePopulationCharacteristics <- function(cdm,
                                          studyPeriod = c(NA, NA),
                                          sex = NULL,
                                          ageGroup = NULL) {
  CohortConstructor::demographicsCohort(cdm = cdm) |>
    CohortConstructor::trimToDateRange(dateRange = studyPeriod) |>
    CohortConstructor::trimDemographics(sex = sex, ageGroup = ageGroup) |>
    CohortCharacteristics::summariseCharacteristics()
}
```

**Comment by martaalcalde** [comment]
(Please @catalamarti  confirm)

Create the previous summarisePopulationCharacteristics function. Just have in mind that:

- Sex is a boolean variable TRUE/FALSE. If true, results should be stratified by sex.
- ageGroup is a list specifying which ageGroups to stratify by

Strata is mixed (i.e., female &&  age < 60; male && age < 60; overall && age <60)
In both cases, the overall (although is not necessarily specified by the user), is included in the result.

- studyPeriod: two dates to trim the observation period. If NULL, start_observation_period and end_observation_period are used. If c(NA, date), start_observation_period and the specified date are used.
