### ISSUE TITLE
Add plotInObservation() example

### ISSUE THREAD

**Issue by martaalcalde** [oxford-pharmacoepi/OmopSketch#86]
Currently, [plotInObservation](https://oxford-pharmacoepi.github.io/OmopSketch/reference/summariseInObservation.html) does not have an example in the website (see, for example, [summariseClinicalRecords](https://oxford-pharmacoepi.github.io/OmopSketch/reference/summariseClinicalRecords.html), which has an example of its functionality).

**Comment by catalamarti** [comment]
This needs https://github.com/oxford-pharmacoepi/OmopSketch/issues/84 to be completed first so we can use the mock function in the example
