### ISSUE TITLE
Modify facet input in ggplot

### ISSUE THREAD

**Issue by martaalcalde** [oxford-pharmacoepi/OmopSketch#87]
Currently, we're using ggplot facet function in a deprecated way (line 68, internalPlot.R). Hence, when using the functions plotInObservation() or plotRecordCount(), which depend on this function, a warning appears: 

<img width="795" alt="Screenshot 2024-09-07 at 18 10 27" src="https://github.com/user-attachments/assets/7b780e00-7969-413e-9551-57e9c0d1c4ac">

**Comment by catalamarti** [comment]
This would be solved when #88 is implemented, closing issue
